
server:
  port: 8081

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: debug

application:
  custom-val: sampleVal2
  mci-url: https://36c7930b-1c7c-4439-bf1d-19900de483fa.mock.pstmn.io/mci
  mci-appli-dtpt-dutj-cd: HW1
  mci-hostname: healthwalet