
server:
  port: 8081

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: debug

application:
  custom-val: sampleVal2
  mci-hostname: health
  mci-appli-dtpt-dutj-cd: HW1
  mci-envr-type-cd: D

  mci-inner-type: JSON
  mci-inner-base-url: https://36c7930b-1c7c-4439-bf1d-19900de483fa.mock.pstmn.io/mci

  mci-outer-type: HFLD
  mci-outer-base-url: http://localhost:3000/api/mci
  mci-outer-frbu-cd: CD
  mci-outer-cmou-dutj-cd: AB
  mci-outer-encode: UTF-8